import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { setTimeout as delay } from 'node:timers/promises';
import { environment, socket, select } from './helpers.mjs';

test('protected admin actions persist bans, revoke old credentials, audit, and gate maintenance', async t => {
  const directory = await mkdtemp(join(tmpdir(), 'beacon-admin-test-'));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const tokenFile = join(directory, 'admin.key');
  await writeFile(tokenFile, 'test-operator-secret', { mode: 0o600 });
  const issued = Date.now() - 10000;
  const auth = { async verify(token) {
    return { id: 'alice', displayName: 'Alice', authAt: Date.now(), ...(token === 'no-iat' ? {} : { issuedAt: token === 'new' ? Date.now() : issued }) };
  } };
  const env = await environment(t, { operations: { enabled: true, listenPort: 0, tokenFile } }, { auth });
  const base = () => `http://127.0.0.1:${env.service.operationsAddress().port}`;
  const admin = async (path, input) => {
    const response = await fetch(base() + path, { method: input ? 'POST' : 'GET', headers: { authorization: 'Bearer test-operator-secret', ...(input ? { 'content-type': 'application/json' } : {}) }, ...(input ? { body: JSON.stringify(input) } : {}) });
    return { status: response.status, body: await response.json() };
  };
  assert.equal((await fetch(base() + '/health')).status, 403);
  const alice = await env.connect('old'); await select(alice);
  const created = await alice.request({ type: 'create_room', name: 'Managed' }, 'room_joined');
  assert.equal((await admin('/rooms/close', { roomId: created.room.id })).status, 200);
  await alice.wait(value => value.type === 'room_closed' && value.roomId === created.room.id);
  assert.equal((await admin('/ban', { playerId: 'alice', until: Date.now() + 60000, reason: 'abuse' })).status, 200);
  const denied = await socket(`ws://127.0.0.1:${env.service.address().port}`);
  const failure = await denied.request({ type: 'auth', token: 'old' }, 'auth_fail');
  assert.equal(failure.code, 'player_banned');
  denied.ws.terminate();
  await env.restart();
  const again = await socket(`ws://127.0.0.1:${env.service.address().port}`);
  assert.equal((await again.request({ type: 'auth', token: 'dev-alice' }, 'auth_fail')).code, 'player_banned');
  again.ws.terminate();
  assert.equal((await admin('/unban', { playerId: 'alice' })).status, 200);
  const restored = await env.connect(); await select(restored);
  assert.equal((await admin('/maintenance', { enabled: true })).status, 200);
  assert.equal((await admin('/ready')).status, 503);
  assert.equal((await restored.request({ type: 'create_room', name: 'Blocked' }, 'error')).code, 'maintenance');
  assert.equal((await admin('/maintenance', { enabled: false })).status, 200);
  assert.equal((await admin('/ready')).status, 200);
  const revokedBefore = Date.now();
  assert.equal((await admin('/revoke', { playerId: 'alice', before: revokedBefore })).status, 200);
  const stale = await socket(`ws://127.0.0.1:${env.service.address().port}`);
  assert.equal((await stale.request({ type: 'auth', token: 'old' }, 'auth_fail')).code, 'token_revoked');
  stale.ws.terminate();
  const unknownIssueTime = await socket(`ws://127.0.0.1:${env.service.address().port}`);
  assert.equal((await unknownIssueTime.request({ type: 'auth', token: 'no-iat' }, 'auth_fail')).code, 'token_revoked');
  unknownIssueTime.ws.terminate();
  await delay(10);
  const renewed = await env.connect('new');
  assert.equal((await renewed.request({ type: 'ping' }, 'pong')).type, 'pong');
  assert.equal((await admin('/ban', { playerId: 'auth0|貓/123', until: Date.now() + 60000, reason: 'moderation' })).status, 200);
  assert.equal((await admin('/unban', { playerId: 'auth0|貓/123' })).status, 200);
  for (let index = 0; index < 140; index++) assert.equal((await admin('/maintenance', { enabled: index % 2 === 0 })).status, 200);
  const completeAudit = await admin('/audit?limit=200');
  assert.ok(completeAudit.body.audit.filter(event => event.action === 'maintenance').length >= 142);
  const audit = completeAudit;
  assert.ok(audit.body.audit.some(event => event.action === 'maintenance'));
  assert.ok(audit.body.audit.some(event => event.action === 'revoke' || event.action === 'revoke_player'));
  const metrics = await admin('/metrics');
  assert.equal(metrics.status, 200);
  assert.equal(typeof metrics.body.stats.rssBytes, 'number');
});

test('shutdown announces drain and lets an established session complete a request', async t => {
  const env = await environment(t, { operations: { drainTimeoutMs: 80 } });
  const alice = await env.connect(); await select(alice);
  const close = env.service.close();
  const draining = await alice.wait(value => value.type === 'server_draining');
  assert.ok(draining.deadline >= Date.now());
  assert.equal((await alice.request({ type: 'ping' }, 'pong')).type, 'pong');
  await close;
  await delay(10);
  assert.equal(alice.ws.readyState, 3);
});
